spring:
  application:
    name: nacos-consumer-feign
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

server:
  port: 9092

management:
  endpoints:
    web:
      exposure:
        include: "*"


# sentinel 防止服务雪崩
feign:
  sentinel:
    enabled: true